"""Atualização do banco de dados total

Revision ID: 3cc3c4bdb3c9
Revises: b3cc6180b562
Create Date: 2025-03-25 16:18:40.935103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc3c4bdb3c9'
down_revision = 'b3cc6180b562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('prioridade', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('data_fechamento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_titulo'), ['titulo'], unique=False)

    op.create_table('arquivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(), nullable=True),
    sa.Column('caminho', sa.String(), nullable=True),
    sa.Column('data_upload', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arquivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arquivo_id'), ['id'], unique=False)

    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('data_envio', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensagem_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensagem_id'))

    op.drop_table('mensagem')
    with op.batch_alter_table('arquivo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arquivo_id'))

    op.drop_table('arquivo')
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_titulo'))
        batch_op.drop_index(batch_op.f('ix_ticket_id'))

    op.drop_table('ticket')
    # ### end Alembic commands ###
