"""Correção de atualização

Revision ID: f383d42f7189
Revises: 3cc3c4bdb3c9
Create Date: 2025-03-25 16:19:24.989308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f383d42f7189'
down_revision = '3cc3c4bdb3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('tipo_usuario', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_nome'), ['nome'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('prioridade', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_titulo'), ['titulo'], unique=False)

    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(), nullable=True),
    sa.Column('caminho', sa.String(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_ticket'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arquivos_id'), ['id'], unique=False)

    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_ticket'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensagens_id'), ['id'], unique=False)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index('ix_ticket_id')
        batch_op.drop_index('ix_ticket_titulo')

    op.drop_table('ticket')
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.drop_index('ix_mensagem_id')

    op.drop_table('mensagem')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('ix_usuario_email')
        batch_op.drop_index('ix_usuario_id')
        batch_op.drop_index('ix_usuario_nome')

    op.drop_table('usuario')
    with op.batch_alter_table('arquivo', schema=None) as batch_op:
        batch_op.drop_index('ix_arquivo_id')

    op.drop_table('arquivo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_ticket', sa.INTEGER(), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('nome_arquivo', sa.VARCHAR(), nullable=True),
    sa.Column('caminho', sa.VARCHAR(), nullable=True),
    sa.Column('data_upload', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arquivo', schema=None) as batch_op:
        batch_op.create_index('ix_arquivo_id', ['id'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('senha', sa.VARCHAR(), nullable=True),
    sa.Column('tipo_usuario', sa.VARCHAR(), nullable=True),
    sa.Column('data_criacao', sa.DATE(), nullable=True),
    sa.Column('empresa', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('ix_usuario_nome', ['nome'], unique=False)
        batch_op.create_index('ix_usuario_id', ['id'], unique=False)
        batch_op.create_index('ix_usuario_email', ['email'], unique=1)

    op.create_table('mensagem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_ticket', sa.INTEGER(), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('mensagem', sa.VARCHAR(), nullable=True),
    sa.Column('data_envio', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.create_index('ix_mensagem_id', ['id'], unique=False)

    op.create_table('ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('titulo', sa.VARCHAR(), nullable=True),
    sa.Column('descricao', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('prioridade', sa.VARCHAR(), nullable=True),
    sa.Column('data_criacao', sa.DATE(), nullable=True),
    sa.Column('data_fechamento', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index('ix_ticket_titulo', ['titulo'], unique=False)
        batch_op.create_index('ix_ticket_id', ['id'], unique=False)

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensagens_id'))

    op.drop_table('mensagens')
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arquivos_id'))

    op.drop_table('arquivos')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_titulo'))
        batch_op.drop_index(batch_op.f('ix_tickets_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_nome'))
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
